In [1]:
#In this project we will automatize the process of gathering the stock data.
# To do this, we will use selenium and some of its modules to perform some webscrapping


import pandas as pd
import numpy as np
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

In [2]:
#Let's now get the driver 

driver = webdriver.Chrome(service = Service(ChromeDriverManager().install()))

url = 'https://fundamentus.com.br/resultado.php'

driver.get(url)

In [3]:
#Let's use our driver to get the html file

table_location = '/html/body/div[1]/div[2]/table'

element = driver.find_element('xpath', table_location)

In [4]:
html_table = element.get_attribute("outerHTML")

In [5]:
#Turning the file into a pandas table
#Notice that we are using the brazilian decimal system. For thousands we use '.' and for decimals ','

df = pd.read_html(str(html_table), thousands='.', decimal= ',')[0]

In [6]:
df

,Papel,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,...,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
0,CFLU4,1000.00,0.00,0.00,0.000,"0,00%",0.0,0.00,0.00,0.00,...,0.00,"8,88%","10,72%",1.10,"17,68%","32,15%",0.0,6.035100e+07,0.06,"8,14%"
1,POPR4,10.17,0.00,0.00,0.000,"0,00%",0.0,0.00,0.00,0.00,...,0.00,"8,66%","5,65%",1.08,"15,25%","19,93%",0.0,5.458030e+08,0.82,"30,93%"
2,CLAN3,0.00,0.00,0.00,0.000,"0,00%",0.0,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","-1,05%",0.0,1.012240e+09,0.00,"-63,96%"
3,CSTB4,147.69,0.00,0.00,0.000,"0,00%",0.0,0.00,0.00,0.00,...,0.00,"40,85%","28,98%",2.60,"22,40%","20,11%",0.0,8.420670e+09,0.14,"31,91%"
4,PMET3,0.00,0.00,0.00,0.000,"0,00%",0.0,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","4,10%",0.0,-2.908630e+08,0.00,"37,74%"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
981,PRBC4,14.54,502.29,40.26,0.000,"0,00%",0.0,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","8,02%",0.0,1.176410e+09,0.00,"-6,01%"
982,UBBR4,7.49,610.27,1.99,0.000,"0,00%",0.0,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,33%",0.0,1.031720e+10,0.00,"10,58%"
983,UBBR11,14.75,1201.81,3.91,0.000,"0,00%",0.0,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,33%",0.0,1.031720e+10,0.00,"10,58%"
984,UBBR3,18.00,1466.61,4.77,0.000,"0,00%",0.0,0.00,0.00,0.00,...,0.00,"0,00%","0,00%",0.00,"0,00%","0,33%",0.0,1.031720e+10,0.00,"10,58%"
985,SQIA3,27.37,2744.55,3.76,3.666,"0,20%",1.5,27.05,43.24,-3.72,...,16.48,"8,48%","0,45%",1.44,"4,04%","0,14%",36660600.0,6.397490e+08,0.67,"46,25%"

In [7]:
#To make the manipulation easier, we are going to turn the tickers into the index (in this table, Papel = ticker)

df = df.set_index('Papel')

In [8]:
df.head()

,Cotação,P/L,P/VP,PSR,Div.Yield,P/Ativo,P/Cap.Giro,P/EBIT,P/Ativ Circ.Liq,EV/EBIT,EV/EBITDA,Mrg Ebit,Mrg. Líq.,Liq. Corr.,ROIC,ROE,Liq.2meses,Patrim. Líq,Dív.Brut/ Patrim.,Cresc. Rec.5a
Papel,,,,,,,,,,,,,,,,,,,,
CFLU4,1000.00,0.0,0.0,0.0,"0,00%",0.0,0.0,0.0,0.0,0.0,0.0,"8,88%","10,72%",1.10,"17,68%","32,15%",0.0,6.035100e+07,0.06,"8,14%"
POPR4,10.17,0.0,0.0,0.0,"0,00%",0.0,0.0,0.0,0.0,0.0,0.0,"8,66%","5,65%",1.08,"15,25%","19,93%",0.0,5.458030e+08,0.82,"30,93%"
CLAN3,0.00,0.0,0.0,0.0,"0,00%",0.0,0.0,0.0,0.0,0.0,0.0,"0,00%","0,00%",0.00,"0,00%","-1,05%",0.0,1.012240e+09,0.00,"-63,96%"
CSTB4,147.69,0.0,0.0,0.0,"0,00%",0.0,0.0,0.0,0.0,0.0,0.0,"40,85%","28,98%",2.60,"22,40%","20,11%",0.0,8.420670e+09,0.14,"31,91%"
PMET3,0.00,0.0,0.0,0.0,"0,00%",0.0,0.0,0.0,0.0,0.0,0.0,"0,00%","0,00%",0.00,"0,00%","4,10%",0.0,-2.908630e+08,0.00,"37,74%"

In [9]:
#Now we are going to choose the features we are going to use in our analysis

df = df[['Cotação', 'EV/EBIT','ROIC', 'Liq.2meses' ]]

In [10]:
df.head()

       Cotação  EV/EBIT    ROIC  Liq.2meses
Papel
CFLU4  1000.00      0.0  17,68%         0.0
POPR4    10.17      0.0  15,25%         0.0
CLAN3     0.00      0.0   0,00%         0.0
CSTB4   147.69      0.0  22,40%         0.0
PMET3     0.00      0.0   0,00%         0.0

In [11]:
#Notice that we have a problem. We need to delete the % symbols and also structure the thousands and decimals symbols to the American pattern

df['ROIC']=df['ROIC'].str.replace('%', '')
df['ROIC']=df['ROIC'].str.replace('.', '')
df['ROIC']=df['ROIC'].str.replace(',', '.')
df['ROIC']=df['ROIC'].astype(float)

df

/var/folders/xv/9wwqryn94_v04yc_tp36ch2c0000gn/T/ipykernel_9130/442532921.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['ROIC']=df['ROIC'].str.replace('.', '')

        Cotação  EV/EBIT   ROIC  Liq.2meses
Papel
CFLU4   1000.00     0.00  17.68         0.0
POPR4     10.17     0.00  15.25         0.0
CLAN3      0.00     0.00   0.00         0.0
CSTB4    147.69     0.00  22.40         0.0
PMET3      0.00     0.00   0.00         0.0
...         ...      ...    ...         ...
PRBC4     14.54     0.00   0.00         0.0
UBBR4      7.49     0.00   0.00         0.0
UBBR11    14.75     0.00   0.00         0.0
UBBR3     18.00     0.00   0.00         0.0
SQIA3     27.37    47.04   4.04  36660600.0

[986 rows x 4 columns]

In [12]:
#Now, with our data ready, let's add our filters to select the stocks 

df = df[df['Liq.2meses']>1000000]
df = df[df['EV/EBIT']>0]
df = df[df['ROIC']>0]

In [13]:
df

       Cotação  EV/EBIT   ROIC   Liq.2meses
Papel
QUAL3     2.88     4.60  13.95   16532200.0
LWSA3     6.00    38.35   2.03   34298700.0
CBAV3     3.81    82.43   0.53   15731500.0
MYPK3    11.33     8.32   6.73   17961600.0
MRVE3     8.46   170.24   0.33  135688000.0
...        ...      ...    ...          ...
RAIL3    23.00    17.80   7.54  333647000.0
CEAB3     5.24     6.86   5.28   18247300.0
MEGA3     8.13    18.34   4.42    8195100.0
CRFB3     9.67     8.87   6.15   85192900.0
SQIA3    27.37    47.04   4.04   36660600.0

[189 rows x 4 columns]

In [18]:
df['ranking_EV/EBIT'] = df['EV/EBIT'].rank(ascending=True)
df['ranking_ROIC'] = df['ROIC'].rank(ascending=False)
df['ranking_total'] = df['ranking_EV/EBIT'] + df['ranking_ROIC']

df.sort_values("ranking_total").head(20)

,Cotação,EV/EBIT,ROIC,Liq.2meses,ranking_EV/EBIT,ranking_ROIC,ranking_total
Papel,,,,,,,
PSSA3,25.61,0.21,60.76,3.291960e+07,1.0,1.0,2.0
PETR4,35.12,2.59,28.95,1.763320e+09,4.0,9.5,13.5
PETR3,38.28,2.74,28.95,4.676050e+08,5.0,9.5,14.5
UNIP6,71.96,4.53,38.68,1.573220e+07,12.5,2.0,14.5
WIZC3,5.07,1.90,24.18,3.999120e+06,3.0,16.0,19.0
FESA4,47.10,4.53,25.57,8.457770e+06,12.5,14.0,26.5
PLPL3,9.06,5.10,30.59,1.300870e+07,23.0,7.0,30.0
VLID3,16.19,4.02,20.64,5.911810e+06,8.0,23.0,31.0
GOAU4,10.51,1.34,19.35,7.601590e+07,2.0,31.0,33.0
KEPL3,9.95,5.50,33.03,1.308400e+07,29.0,5.0,34.0
GGBR3,20.25,3.42,19.39,1.093330e+06,6.0,29.5,35.5
GGBR4,22.18,3.70,19.39,2.047420e+08,7.0,29.5,36.5
TASA4,14.85,5.04,24.33,6.472080e+06,22.0,15.0,37.0
LEVE3,36.43,5.79,36.32,2.616010e+07,37.5,4.0,41.5
VALE3,70.32,4.62,20.11,1.626320e+09,17.0,25.0,42.0
LREN3,12.27,4.08,17.55,2.973940e+08,9.0,36.0,45.0
PRNR3,10.45,4.91,20.01,2.584140e+06,21.0,26.0,47.0
AURA33,32.04,5.15,19.72,1.447450e+06,24.0,27.0,51.0
CMIN3,5.33,6.02,28.49,4.292170e+07,40.0,11.0,51.0
CMIG4,12.24,4.44,16.35,1.063870e+08,10.0,43.5,53.5